# ----------------------------------------------------------------------------
# Amiga-os3-specific options
# ----------------------------------------------------------------------------

override TARGET=amigaos3
#override  TARGET=framebuffer

override SUBTARGET=

override COMMON_WARNFLAGS =
#override GCCSDK_INSTALL_ENV=/usr/local/amiga/m68k-amigaos
#override PKG_CONFIG=PKG_CONFIG_LIBDIR="$(GCCSDK_INSTALL_ENV)/lib/pkgconfig" pkg-config

	#RTG 			:= YES
	AGA 			:= 685
	#AGA 			:= 676
	DEBUG 			:= NO
	TTF 			:= YES
	LIBNIX 			:= NO
	USE_CACHE		:= YES
	NETSURF_USE_DUKTAPE := YES

ifeq ($(HOST),ixemul-aga)
override RTG:=NO
else
override RTG:=YES
endif

ifeq ($(USE_CACHE),YES)
override NETSURF_FS_BACKING_STORE := YES
else
override NETSURF_FS_BACKING_STORE := NO
endif

PPC := NO

ifeq ($(DEBUG),YES)
	CFLAGS += -DDEBUG_FETCH_VERBOSE
	#CFLAGS +=  -DFBTK_LOGGING
	#CFLAGS +=  -DDEBUG_SCHEDULER
else
	#CFLAGS += -DNDEBUG
endif

ifeq ($(TTF),YES)
	override  NETSURF_FB_FONTLIB := freetype
else
	override  NETSURF_FB_FONTLIB := internal
endif

ifeq ($(NETSURF_FS_BACKING_STORE),YES)
	CFLAGS += -DCACHE
endif


ifeq ($(PPC),YES)
	GCCVER := 2
	CC_MINOR := 2
	CC := ppc-amigaos-gcc -g
	CFLAGS += -IADE:include -ITyp:usr/local/amiga/m68k-amigaos/sys-include -LTyp:usr/local/amiga/m68k-amigaos/lib -Ityp:opt/share/include
else
ifeq ($(HOST),clib2)
	PREF=/opt/netsurf/m68k-unknown-amigaos
	GCCSDK_INSTALL_ENV = $(PREF)/m68k-unknown-amigaos/env
	GCCSDK_INSTALL_CROSSBIN = $(PREF)/env/bin
	CC := $(PREF)/cross/bin/m68k-unknown-amigaos-gcc
	AS := $(PREF)/cross/bin/m68k-unknown-amigaos-as
	CFLAGS += -D__clib2__ -I$(PREF)/cross/m68k-unknown-amigaos/include -I$(PREF)/env/include \
		  -I$(PREF)/cross/m68k-unknown-amigaos/sys-include
	PKG_CONFIG := PKG_CONFIG_PATH ="/opt/netsurf/share/lib/pkgconfig" pkg-config
	PKG_CONFIG_PATH+="$(GCCSDK_INSTALL_ENV)/lib/pkgconfig" pkg-config	
else
	#GCCVER := 2
	#CC_MINOR := 2
	GCCSDK_INSTALL_ENV = /usr/local/amiga/m68k-amigaos
	GCCSDK_INSTALL_CROSSBIN = /usr/local/amiga/m68k-amigaos/bin	
	PKG_CONFIG := PKG_CONFIG_LIBDIR="$(GCCSDK_INSTALL_ENV)/lib/pkgconfig" pkg-config
ifeq ($(LIBNIX),YES)
	#CC := /usr/local/amiga/bin/m68k-amigaos-gcc-2.95.3 -noixemul  -pipe
	CC := /usr/local/amiga/bin/m68k-amigaos-gcc -noixemul -pipe
else
	CC := /usr/local/amiga/bin/m68k-amigaos-gcc-3.4.0 -pipe
endif

endif

endif

 # Optimisation levels
ifeq ($(DEBUG),NO)
 	CFLAGS += -s -O2 -mnobitfield -pipe
else
	CC += -g
	CFLAGS += -g	
endif

ifeq ($(USE_FPU),NO)
 	CFLAGS += -msoft-float
else
 	CFLAGS += -m68020-60
endif
	
ifeq ($(LIBNIX),YES)
	CC += -noixemul
	CFLAGS += -noixemul
endif

ifeq ($(RTG),YES)
	CFLAGS += -DRTG
else ifeq ($(AGA),685) 
	CFLAGS += -DAGA685 -DAGA
else ifeq ($(AGA),676)
	CFLAGS += -DAGA676 -DAGA
endif

override NETSURF_UA_FORMAT_STRING := "NetSurf/%d.%d (%s,%s)"

# Force using glibc internal iconv implementation instead of external libiconv
# Valid options: YES, NO
NETSURF_USE_LIBICONV_PLUG := NO
NETSURF_USE_UTF8PROC := YES

# Enable NetSurf's use of librosprite for displaying RISC OS Sprites
# Valid options: YES, NO, AUTO
NETSURF_USE_ROSPRITE := NO

# Enable NetSurf's use of libwebp for displaying WebPs
# Valid options: YES, NO
NETSURF_USE_WEBP := NO

# Enable NetSurf's use of libsvgtiny for displaying SVGs
# Valid options: YES, NO
NETSURF_USE_NSSVG := NO

override  NETSURF_FB_FRONTEND := sdl
override  NETSURF_FB_RESPATH_sdl := "PROGDIR:Resources/"
override  NETSURF_STRIP_BINARY := NO
override  NETSURF_USE_VIDEO := NO
override  NETSURF_FB_FONTPATH := "PROGDIR:Fonts/"

# define additional CFLAGS and LDFLAGS requirements for pkg-configed libs here
NETSURF_FEATURE_HUBBUB_CFLAGS := -DWITH_HUBBUB
NETSURF_FEATURE_BMP_CFLAGS := -DWITH_BMP
NETSURF_FEATURE_GIF_CFLAGS := -DWITH_GIF
NETSURF_FEATURE_JS_CFLAGS := -DWITH_JS -DJS_HAS_FILE_OBJECT=0
NETSURF_FEATURE_MOZJS_CFLAGS := -DWITH_MOZJS -DJS_HAS_FILE_OBJECT=0
