/* build-clib2-amigaos3/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "7b43826c801d0c39244a8d5d2e26aa23"

/* Revision testament checksum:
 * MD5:7b43826c801d0c39244a8d5d2e26aa23
 */

/* Revision testament: */
#define USERNAME "root"
#define GECOS "root"
#define WT_ROOT "/media/sf_E_DRIVE/projects/netsurf/"
#define WT_HOSTNAME "debian"
#define WT_COMPILEDATE "27.02.2016"
#define WT_BRANCHPATH "NetSurf-68k"
#define WT_REVID "3dc6d9bacb1e78fd470e15d0b25425121593760e"
#define WT_MODIFIED 991
#define WT_MODIFICATIONS {"null"}
#endif
